.flake8
.github/workflows/lint-backend.yml
.github/workflows/lint.yml
.pylintrc
.vscode/settings.json
core/api/serializers/auth.py
core/api/serializers/chemicals.py
core/api/serializers/usage.py
core/api/tests/factories.py
core/api/tests/test_chemicals.py
core/api/tests/test_usages.py
core/api/views/chemicals.py
core/import_data/import_ozone_data.py
core/import_data/import_proposals.py
core/import_data/import_records_cp_db.py
core/import_data/import_records_xlsx.py
core/import_data/utils.py
core/management/commands/import_resources.py
core/templatetags/settings_value.py
core/tests.py
core/views.py
docs/install_develop.md
multilateralfund/settings.py
multilateralfund/views.py
requirements-dev.txt
requirements.txt

Pylint on pull requests

---

frontend/src/components/shared/ManageChemicalModal.tsx
frontend/src/components/table/TableData.tsx
frontend/src/pages/ReportsPage.tsx
frontend/src/services/api.ts
frontend/src/services/endpoints/reportEndpoints.ts
frontend/src/slices/reportSlice.ts
frontend/src/types/Reports.ts

- Refactoring substances modal
- Refactoring table to display blends

Add blends

---

core/admin/substance.py
core/api/tests/factories.py
core/api/tests/test_chemicals.py
core/api/urls.py
core/api/views/chemicals.py
core/import_data/import_ozone_data.py

Add uncontrolled group and section C endpoint

---

.env.example
core/api/urls.py
core/templates/admin/base_site.html
docs/development_guide.md
multilateralfund/settings.py

Rename api docs, add it to admin and readme. Fix scheme problem.

---

core/api/serializers/usage.py
core/api/tests/test_usages.py

[#20256](https://helpdesk.eaudeweb.ro/issues/20256)

Update get usage endpoint

---

core/admin/project_submission.py
core/api/filters/project.py
core/api/serializers/project.py
core/api/tests/test_projects.py
core/api/utils.py
core/api/views/projects.py
multilateralfund/settings.py

[#20351](https://helpdesk.eaudeweb.ro/issues/20351)

Updated filters

---

core/import_data/import_progress_reports.py
core/import_data/import_project_resources.py
core/import_data/utils.py

[#20321](https://helpdesk.eaudeweb.ro/issues/20321)

Fixed import projects

---

core/api/tests/test_chemicals.py
core/api/views/chemicals.py

refs [#24201](https://helpdesk.eaudeweb.ro/issues/24201)

Excluded legacy chemicals from api list views

---

frontend/src/components/manage/Blocks/Section/SectionA/View/View.tsx

- refs https://helpdesk.eaudeweb.ro/issues/24183
@david-batranu should I do this for section B as well?

Filter empty rows in section A of reports past 2023

---

core/api/tests/conftest.py
core/api/tests/test_cp_archive.py
core/api/tests/test_cp_export.py
core/api/urls.py
core/api/views/cp_archive.py
frontend/src/components/manage/Blocks/CountryProgramme/CPView.tsx
frontend/src/components/manage/Blocks/Section/SectionA/View/View.tsx

D. from [#24346](https://helpdesk.eaudeweb.ro/issues/24346)
Added endpoints for exporting archive records:
GET
```
/api/country-programme-archive/export/
/api/country-programme-archive/print/
```
params = cp_report_id (archive id)

Added Api for exporting cp reports archive

---

core/import_data/import_admde.py
core/import_data/mapping_names_dict.py
frontend/src/components/manage/Blocks/Section/AdmD/Create/Create.tsx
frontend/src/components/manage/Blocks/Section/AdmD/View/View.tsx

- refs https://helpdesk.eaudeweb.ro/issues/24346 (A,B,C)

Fix format errors in CP

---

frontend/src/@types/user_types.ts
frontend/src/components/manage/Blocks/CountryProgramme/CPCreate.tsx
frontend/src/components/manage/Blocks/CountryProgramme/CPEdit.tsx
frontend/src/components/manage/Blocks/CountryProgramme/CPEmpty.tsx
frontend/src/components/manage/Blocks/CountryProgramme/CPHeader.tsx
frontend/src/components/manage/Blocks/CountryProgramme/CPListing.tsx
frontend/src/components/manage/Blocks/Section/ReportInfo/Create/Create.tsx
frontend/src/components/manage/Blocks/Section/ReportInfo/View/View.tsx

- refs https://helpdesk.eaudeweb.ro/issues/24171

Show/Hide CP elements based on user_type

---

frontend/src/components/manage/Blocks/Section/SectionA/Create/schema.tsx
frontend/src/components/manage/Blocks/Section/SectionA/View/schema.tsx
frontend/src/themes/styles/components/ag-grid/cell.css
frontend/src/themes/styles/components/ag-grid/header.css
frontend/src/themes/styles/components/ag-grid/row.css
frontend/src/themes/styles/components/ag-grid/variables.css

Change border color to bg-300; right align sub-headers

---

frontend/src/components/manage/Blocks/Section/SectionA/View/View.tsx
frontend/src/components/manage/Blocks/Section/SectionB/View/View.tsx
frontend/src/components/manage/Blocks/Section/SectionC/View/View.tsx

I also moved the alerts to be the first thing in the page, according to figma.

Add empty rows checkbox for all formats

---

frontend/pnpm-lock.yaml
frontend/src/components/manage/Blocks/CountryProgramme/CPComments.tsx
frontend/src/components/manage/Blocks/CountryProgramme/CPCreate.tsx
frontend/src/components/manage/Blocks/CountryProgramme/CPEdit.tsx
frontend/src/components/manage/Blocks/CountryProgramme/CPSectionWrapper.tsx
frontend/src/components/manage/Blocks/CountryProgramme/CPView.tsx
frontend/src/components/manage/Blocks/Section/AdmB/Create/Create.tsx
frontend/src/components/manage/Blocks/Section/AdmB/View/View.tsx
frontend/src/components/manage/Blocks/Section/AdmC/Create/Create.tsx
frontend/src/components/manage/Blocks/Section/ReportInfo/View/View.tsx
frontend/src/components/manage/Blocks/Section/SectionA/Create/Create.tsx
frontend/src/components/manage/Blocks/Section/SectionA/View/View.tsx
frontend/src/components/manage/Blocks/Section/SectionB/Create/Create.tsx
frontend/src/components/manage/Blocks/Section/SectionB/View/View.tsx
frontend/src/components/manage/Blocks/Section/SectionC/Create/Create.tsx
frontend/src/components/manage/Blocks/Section/SectionD/Create/Create.tsx
frontend/src/components/manage/Blocks/Section/SectionD/View/View.tsx
frontend/src/components/manage/Blocks/Section/SectionE/Create/Create.tsx
frontend/src/components/manage/Blocks/Section/SectionE/View/View.tsx
frontend/src/components/manage/Blocks/Section/SectionReportedSelect.tsx
frontend/src/themes/styles/components/mui/MuiButtonBase.css

In this PR:
- notes the first item in the header, above buttons and checkboxes;
- improved margins and paddings;
- improved old report models footnotes;
- hide Comments on Report Info section;

Sections layout changes

---

frontend/src/components/manage/Blocks/Section/SectionB/Create/Create.tsx
frontend/src/components/manage/Blocks/Section/SectionB/Create/CreateBlend.tsx

- refs https://helpdesk.eaudeweb.ro/issues/24525 #1

Don't include Annex F substances in section B in format 2019-2022

---

frontend/src/components/manage/Blocks/Section/SectionA/Create/Create.tsx

- refs https://helpdesk.eaudeweb.ro/issues/24525 point 2

Section A - Show only substances from 'Annex C, Group I' for all formats up to 2023

---

core/api/serializers/chemicals.py
core/api/serializers/cp_record.py
core/api/serializers/cp_usage.py
core/api/tests/conftest.py
core/api/tests/test_cp_record.py
core/models/base.py

[#24639](https://helpdesk.eaudeweb.ro/issues/24639)

Add gwp odp value

---

frontend/src/components/manage/Blocks/CountryProgramme/CPListing.tsx

- refs https://helpdesk.eaudeweb.ro/issues/24689

Hide submission tab for country_user

---

frontend/src/components/manage/Blocks/Section/SectionC/Create/Create.tsx

- refs https://helpdesk.eaudeweb.ro/issues/24183#note-20

Update section C dropdowns

---

frontend/src/components/manage/Blocks/CountryProgramme/CPCreate.tsx
frontend/src/components/manage/Blocks/CountryProgramme/typesCPCreate.ts
frontend/src/components/manage/Blocks/Section/ReportInfo/Create/Create.tsx

- Refs https://helpdesk.eaudeweb.ro/issues/24781 point 3

Reporting year dropdown

---

frontend/src/components/manage/Blocks/Section/ReportInfo/Create/Create.tsx
frontend/src/components/manage/Blocks/Section/SectionA/Create/Create.tsx
frontend/src/components/manage/Blocks/Section/SectionA/View/View.tsx
frontend/src/components/manage/Blocks/Section/SectionA/sectionColumnsDef.ts
frontend/src/components/manage/Blocks/Section/SectionB/Create/Create.tsx
frontend/src/components/manage/Blocks/Section/SectionB/View/View.tsx
frontend/src/components/manage/Blocks/Section/SectionB/View/schema.tsx
frontend/src/components/manage/Blocks/Section/SectionB/sectionColumnsDef.tsx
frontend/src/config/Table/columnsDef/usagesColDef.ts

- refs https://helpdesk.eaudeweb.ro/issues/24781 point 8 & 8.1 (from word file)

Remove other rows

---

core/api/export/cp_calculated_amount.py
core/api/tests/test_cp_export.py
core/api/urls.py
core/api/views/cp_records_export.py
core/models/country_programme.py

[#21323](https://helpdesk.eaudeweb.ro/issues/21323#note-10)

Added export for cp report consumption amount

---

.github/workflows/docker-build.yml
core/api/serializers/cp_report.py
core/api/tests/test_cp_report.py
core/api/tests/test_cp_report_comments.py
core/api/tests/test_settings.py
core/api/views/cp_reports.py
core/api/views/settings.py
core/tasks.py
docker-compose.develop.yml
docker-compose.override.test.yml
docker-compose.yml
docker/celery.docker
multilateralfund/__init__.py
multilateralfund/celery.py
multilateralfund/settings.py
requirements.txt

Refs https://helpdesk.eaudeweb.ro/issues/24753

Send mail async tasks

---

frontend/src/@types/store.d.ts
frontend/src/components/manage/Blocks/Section/SectionB/Create/Create.tsx
frontend/src/components/manage/Blocks/Section/SectionB/Create/CreateBlend.tsx
frontend/src/components/manage/Blocks/Section/SectionC/Create/Create.tsx
frontend/src/slices/createCPReportsSlice.ts

- Refs https://helpdesk.eaudeweb.ro/issues/24781 point 13

Section c substances

---

core/api/tests/test_chemicals.py
core/api/views/chemicals.py
frontend/src/components/manage/AgWidgets/CellDateWidget.tsx
frontend/src/components/manage/Blocks/Section/SectionB/Create/CreateBlend.tsx

[#24781](https://helpdesk.eaudeweb.ro/issues/24781)
Component name is not mandatory anymore for other substances

Updated add blend

---

frontend/src/@types/store.d.ts
frontend/src/app/country-programme/settings/page.tsx
frontend/src/components/manage/Blocks/CountryProgramme/CPSettings.tsx
frontend/src/slices/createCommonSlice.ts
multilateralfund/settings.py

- refs https://helpdesk.eaudeweb.ro/issues/24753

Add settings page; Add send email setting checkbox

---

frontend/src/components/manage/AgCellRenderers/AgCellRenderer.tsx
frontend/src/components/manage/Blocks/Section/SectionA/Create/schema.tsx
frontend/src/components/manage/Blocks/Section/SectionB/Create/CreateBlend.tsx
frontend/src/components/manage/Blocks/Section/SectionB/Create/schema.tsx
frontend/src/components/manage/Blocks/Section/SectionC/Create/schema.tsx
frontend/src/components/manage/Blocks/Section/SectionE/Create/schema.tsx

- Refs https://helpdesk.eaudeweb.ro/issues/24781 point 2

Remove row menu

---

core/api/views/countries.py
core/import_data/import_chemicals.py
core/import_data/utils.py

Remove `r134a` from blends.
Set role `Secretariat` for initial import user. 
Remove the Article 2 countries from the list of countries (filter).

Some feedback changes

---

core/api/serializers/cp_report.py
core/api/serializers/cp_usage.py
core/api/tests/test_cp_report_validation.py
core/api/validations/cp_reports_validations.py
core/api/views/cp_reports.py

Sections A and B (2023 or later) - check if use values are negative.

Validation for usage by sector data

---

frontend/src/components/manage/AgWidgets/CellValidationWidget/CellValidationAlert.tsx
frontend/src/components/manage/AgWidgets/CellValidationWidget/CellValidationWidget.tsx
frontend/src/components/manage/Form/Table.tsx
frontend/src/components/ui/SectionTab/SectionErrorIndicator.tsx
frontend/tailwind.config.ts

- refs https://helpdesk.eaudeweb.ro/issues/24781? point 20

Change warning colors

---

frontend/src/@types/user_types.ts
frontend/src/app/country-programme/export-data/page.tsx
frontend/src/components/manage/Blocks/CountryProgramme/CPExport.tsx
frontend/src/components/manage/Blocks/CountryProgramme/CPHeader.tsx
frontend/src/components/manage/Blocks/CountryProgramme/CPListing.tsx
frontend/src/components/theme/Header/HeaderNavigation.tsx

- refs https://helpdesk.eaudeweb.ro/issues/21323#note-14

Implement export page

---

core/api/views/cp_reports.py
core/import_data/resources/adm_columns.json
frontend/src/components/manage/Blocks/Section/AdmB/Create/schema.tsx
frontend/src/components/manage/Blocks/Section/AdmB/View/schema.tsx
frontend/src/components/manage/Blocks/Section/AdmC/Create/schema.tsx
frontend/src/components/manage/Blocks/Section/AdmC/View/schema.tsx

I added a new column in adm columns (admB and AdmC)
Now the remarks column does not need to be added manually by the frontend and it should be easier to save the value for it

Added remarks in adm columns

---

frontend/src/components/manage/Blocks/CountryProgramme/CPExport.tsx
frontend/src/themes/styles/components/mui/MuiButtonBase.css
frontend/src/themes/styles/components/mui/MuiSelect.css

- refs  https://helpdesk.eaudeweb.ro/issues/21323#note-14

Improve CP export inputs

---

core/api/export/cp_calculated_amount.py
core/api/export/cp_data_extraction_all.py
core/api/tests/test_cp_export.py
core/api/views/cp_records_export.py
core/models/country_programme.py

Export updates

---

core/api/export/base.py
core/api/export/cp_report_new.py
core/api/export/section_export.py
core/api/tests/test_cp_export.py
core/api/views/cp_records_export.py
frontend/src/components/manage/Blocks/CountryProgramme/CPView.tsx

Add conversion to cp report export

---

core/admin/country_programme_archive.py
core/api/export/cp_data_extraction_all.py
core/api/views/cp_records_export.py
core/api/views/utils.py
core/models/base_country_programme.py
core/models/country_programme.py

Removed draft reports from statistics (extractions)

---

core/api/export/base.py
core/api/export/cp_calculated_amount.py
core/api/export/cp_data_extraction_all.py
core/api/export/cp_report_hfc_hcfc.py
core/api/export/cp_report_new.py
core/api/export/cp_report_old.py
core/api/export/section_export.py
core/api/serializers/usage.py

Updated export align

---

core/api/tests/test_chemicals.py
core/api/views/chemicals.py
core/models/blend.py
frontend/src/components/manage/Blocks/Section/SectionB/Create/CreateBlend.tsx

[#24781](https://helpdesk.eaudeweb.ro/issues/24781#note-20)
Updated GET /api/blends/similar/
Now it returns a list of blends

Updated get similar blends response list

---

core/api/views/cp_records.py
frontend/src/@types/api_country-programme_records.ts
frontend/src/components/manage/AgCellRenderers/AgTextCellRenderer.tsx
frontend/src/components/manage/AgCellRenderers/AgTextDiffRenderer.tsx
frontend/src/components/manage/AgComponents/AgTooltipComponent.tsx
frontend/src/components/manage/AgComponents/AgTooltipDiffComponent.tsx
frontend/src/components/manage/Blocks/Section/SectionA/ViewDiff/schema.tsx
frontend/src/components/manage/Blocks/Section/SectionB/ViewDiff/schema.tsx
frontend/src/components/manage/Blocks/Section/SectionC/ViewDiff/schema.tsx
frontend/src/components/manage/Blocks/Section/SectionE/ViewDiff/schema.tsx
frontend/src/components/manage/Utils/diffUtils.ts
frontend/src/config/Table/columnsDef/index.ts
frontend/src/config/Table/components.ts
frontend/src/config/Table/renderers.ts
frontend/src/themes/styles/components/ag-grid/diff.css

- refs https://helpdesk.eaudeweb.ro/issues/24167#note-21

Truncate Remarks column text in all CP Tabels

---

frontend/src/components/manage/AgCellRenderers/AgTextDiffRenderer.tsx
frontend/src/components/manage/AgComponents/AgTooltipDiffComponent.tsx
frontend/src/components/manage/Blocks/Section/SectionA/Create/schema.tsx
frontend/src/components/manage/Blocks/Section/SectionA/View/schema.tsx
frontend/src/components/manage/Blocks/Section/SectionA/ViewDiff/View.tsx
frontend/src/components/manage/Blocks/Section/SectionB/Create/schema.tsx
frontend/src/components/manage/Blocks/Section/SectionB/View/schema.tsx
frontend/src/components/manage/Blocks/Section/SectionB/sectionColumnsDef.tsx
frontend/src/components/manage/Blocks/Section/SectionC/ViewDiff/schema.tsx
frontend/src/components/manage/Form/Table.tsx
frontend/src/components/manage/Utils/diffUtils.ts
frontend/src/config/Table/columnsDef/index.ts
frontend/src/themes/styles/components/ag-grid/diff.css

Implemented:
- Re-align sections remarks col text to the left;
- Add Close button on tooltip;
- Close tooltip on Escape key;
- Don't close tooltip when clicking on it;

Remarks col changes

---

core/api/tests/test_bp_comments.py
core/api/views/business_plan.py
core/tasks.py

https://helpdesk.eaudeweb.ro/issues/25311
Points 1 and 2 done.

BP send mail events

---

core/api/export/cp_data_extraction_all.py
core/api/export/cp_report_hfc_hcfc.py
core/api/views/cp_records_export.py
core/import_data/mapping_names_dict.py
core/models/base_country_programme.py

Extraction-All :
HCFC / HFC extractions:

Updated extraction exports

---

core/api/tests/test_business_plans.py
core/api/views/business_plan.py
core/tasks.py

When a secretariat user approves / rejects a business plan, the agency user will receive an email notification.

Status update mail and small fixes

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/components/manage/Blocks/CountryProgramme/CPCreate.tsx
frontend/src/components/manage/Blocks/CountryProgramme/CPHeader.tsx
frontend/src/components/manage/Blocks/CountryProgramme/CPListing.tsx
frontend/src/components/manage/Blocks/Section/SectionA/TableDataSelector.tsx
frontend/src/components/manage/Blocks/Section/SectionA/View/View.tsx
frontend/src/components/manage/Blocks/Section/SectionB/View/View.tsx
frontend/src/components/theme/Footer/AuthorizedFooter.tsx
frontend/src/components/theme/Header/HeaderNavigation.tsx
frontend/src/components/ui/SimpleTable/SimpleTable.tsx
frontend/src/themes/styles/print.css

Points 1 through 8 from `6. CP Data Testing Comments(June 13, 2026)`

June 13 feedback

---

core/import_data/set_bp_clusters.py
core/management/commands/import_business_plans.py
requirements.txt

[21779](https://helpdesk.eaudeweb.ro/issues/21779)

Set bp clusters

---

core/api/export/cp_reports_list.py
core/api/urls.py
core/api/views/cp_records_export.py
core/api/views/utils.py

[#25846](https://helpdesk.eaudeweb.ro/issues/25846)

Added api for report list export

---

frontend/src/app/replenishment/invoices/[period]/page.jsx
frontend/src/app/replenishment/invoices/page.jsx
frontend/src/app/replenishment/payments/[period]/page.jsx
frontend/src/app/replenishment/payments/page.jsx
frontend/src/app/replenishment/status-of-contributions/annual/[year]/page.jsx
frontend/src/app/replenishment/status-of-contributions/summary/page.jsx
frontend/src/app/replenishment/status-of-contributions/triennial/[period]/page.jsx
frontend/src/components/manage/Blocks/Replenishment/StatusOfContribution/DisputedContributionDialog.jsx
frontend/src/components/manage/Blocks/Replenishment/StatusOfContribution/Indicators.jsx
frontend/src/components/manage/Blocks/Replenishment/StatusOfContribution/SCAnnual.jsx
frontend/src/components/manage/Blocks/Replenishment/StatusOfContribution/SCSummary.jsx
frontend/src/components/manage/Blocks/Replenishment/StatusOfContribution/SCTriennial.jsx
frontend/src/components/manage/Blocks/Replenishment/StatusOfContribution/SCView.jsx
frontend/src/components/manage/Blocks/Replenishment/StatusOfContribution/utils.js
frontend/src/components/manage/Blocks/Replenishment/Table/HeaderCells.jsx

Refs https://helpdesk.eaudeweb.ro/issues/25646
- add functioning Indicators;
- add mock "disputed contribution" pop-up;
- improve print layout;
- treat and display values in (-1,1) range as 0;

Status of contributions new specs

---

core/api/tests/test_replenishment.py
core/api/views/replenishment.py
frontend/src/components/manage/Blocks/Replenishment/Dashboard/DashboardView.jsx
frontend/src/components/manage/Blocks/Replenishment/SAView/SAView.jsx

- refs https://helpdesk.eaudeweb.ro/issues/25471
- add edit for the dashboard data
- only return closed triennials data

Replenishment dashboard changes

---

core/import_data/import_replenishments.py

- Imported replenishments have 2 versions, latest is final

Import changes

---

core/api/export/cp_data_extraction_all.py
core/api/tests/test_cp_export.py
core/api/views/cp_records_export.py
core/api/views/utils.py
core/models/base_country_programme.py
frontend/src/components/manage/Blocks/CountryProgramme/CPExport.tsx

Updated param list for export extraction all
**GET** _/api/country-programme/data-extraction-all/export/_
new params:
min_year -> number (optional)
max_year ->  number (optional)

Updated extraction all (added year range)

---

frontend/src/app/replenishment/ReplenishmentHeading.jsx
frontend/src/components/manage/Blocks/Replenishment/ConfirmDialog.jsx
frontend/src/components/manage/Blocks/Replenishment/SAView/SAHeading.jsx
frontend/src/components/manage/Blocks/Replenishment/SAView/SAView.jsx
frontend/src/components/ui/SimpleSelect/SimpleSelect.tsx
frontend/src/contexts/Replenishment/ReplenishmentProvider.jsx

Implemented:
- new Add Period button with a Confirm Dialog; POST it to endpoint `/api/replenishment/replenishments ` and redirect to `/replenishment/scale-of-assessment/[new-period]`
- display Add New Period button only if it's the last available period and version is final
- hide Mark as Final checkbox and Save Changes submit button if version is final;
- fix Period Selector; period was not properly displayed when refreshing page;

SoA improvements

---

core/api/serializers/business_plan.py
core/api/tests/test_business_plans.py
core/api/views/business_plan.py

`BP create` -> Don't let the user to create comment.
`BP update` -> Don't let the agency user to update comment.

Comment submit validations

---

core/api/filters/business_plan.py
core/api/serializers/business_plan.py
core/api/views/business_plan.py
frontend/src/components/manage/Blocks/BusinessPlans/Activities.tsx

Updated response for GET /business-plan-activity/
Updated docs for get CRUDL Activity + CU Business Plan

Updated docs for bp endpoints

---

core/api/serializers/business_plan.py
frontend/src/components/manage/Blocks/BusinessPlans/Activities.tsx
frontend/src/components/manage/Blocks/Table/BusinessPlansTable/schema.tsx

Updated name of the substances list field from bp activity details:
substances -> substances_display

Updated bp activity detail serializer

---

core/api/export/replenishment.py
core/api/serializers/replenishment.py
core/api/views/replenishment.py
core/models/replenishment.py
frontend/src/app/replenishment/scale-of-assessment/[period]/page.jsx
frontend/src/components/manage/Blocks/Replenishment/SAView/SAView.jsx

- refs https://helpdesk.eaudeweb.ro/issues/25488

[Replenishment] Export SoA data to excel

---

core/api/export/cp_data_extraction_all.py
core/api/tests/test_cp_export.py
core/api/views/cp_records_export.py
core/api/views/utils.py
core/models/base_country_programme.py

[25988](https://helpdesk.eaudeweb.ro/issues/25988)
Updated structure for export all functionality
Updated consumption calculation

CP: Updated export all

---

core/import_data/import_chemicals.py

[25988](https://helpdesk.eaudeweb.ro/issues/25988)

Set group for substances that are related to imported pre-blended polyol

---

frontend/src/components/manage/Blocks/BusinessPlans/ActivitiesFilters.tsx
frontend/src/components/manage/Blocks/BusinessPlans/BPList/ActivitiesFiltersSelectedOpts.tsx
frontend/src/components/manage/Blocks/BusinessPlans/BPList/BPListActivities.tsx
frontend/src/components/manage/Blocks/Table/BusinessPlansTable/BusinessPlansTable.tsx
frontend/src/themes/styles/components/ag-grid/_index.css
frontend/src/themes/styles/components/ag-grid/toolbar.css

Refs https://helpdesk.eaudeweb.ro/issues/25078
- Displayed filters' selected options separately
- Rearrange filters, according to the design

Style business plans activities filters

---

core/api/tests/test_business_plans.py
core/api/urls.py
core/api/views/business_plan.py
core/api/views/cp_records.py
core/api/views/utils.py

Point 4 from https://helpdesk.eaudeweb.ro/issues/25076

BP activities diff

---

core/api/tests/test_replenishment.py
core/api/views/replenishment.py
core/import_data/import_status_of_contributions.py
frontend/src/components/manage/Blocks/Replenishment/Dashboard/DashboardView.jsx
frontend/src/components/manage/Blocks/Replenishment/Dashboard/useGetDashboardData.js
frontend/src/components/manage/Blocks/Replenishment/Inputs.jsx

- Add start year and end year for external income
- Fix editing bug thanks to @david-batranu

[Replenishment] Fix dashboard edit

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/manage/Blocks/Table/BusinessPlansTable/BusinessPlansTable.tsx
frontend/src/components/manage/Blocks/Table/BusinessPlansTable/CommentsTagList.tsx
frontend/src/components/manage/Blocks/Table/BusinessPlansTable/schema.tsx
frontend/src/themes/styles/components/mui/MuiTooltip.css

Refs https://helpdesk.eaudeweb.ro/issues/25073
- Displayed comments types in tags in Business Plans table

display comments tags in bp table (#25073)

---

frontend/src/components/manage/Blocks/Table/BusinessPlansTable/BusinessPlansTable.tsx

Refs https://helpdesk.eaudeweb.ro/issues/25078
- Added "After year" column in bp table

After year column in bp table

---

frontend/src/components/manage/Blocks/Table/BusinessPlansTable/schema.tsx

Refs https://helpdesk.eaudeweb.ro/issues/25078
- Reorder bp table's columns - title should come after subsector

Reorder columns of bp table

---

core/api/tests/test_business_plans.py
core/api/views/business_plan.py

https://helpdesk.eaudeweb.ro/issues/26190#note-6

Fix BP export filename

---

frontend/src/components/manage/AgWidgets/CellAdmDateWidget.tsx
frontend/src/components/manage/AgWidgets/CellDateWidget.tsx

Attempts to fix:
https://helpdesk.eaudeweb.ro/issues/25988 - point 7

Making year selection default in DatePicker

---

core/api/filters/comment_type.py
core/api/tests/test_comment_types.py
core/api/views/comment_types.py

https://helpdesk.eaudeweb.ro/issues/25073#note-12

Add comment type filter

---

core/api/filters/business_plan.py
core/api/tests/test_business_plans.py

Fix comment type filter

---

core/api/serializers/business_plan.py
core/api/tests/test_business_plans.py
core/api/utils.py
core/api/views/settings.py

https://helpdesk.eaudeweb.ro/issues/26572

BP project sector/type validation

---

core/api/serializers/base.py
core/api/serializers/chemicals.py
core/models/base.py
core/models/blend.py

15 -> [#25988](https://helpdesk.eaudeweb.ro/issues/25988)

Updated blend group name

---

core/api/serializers/base.py
core/api/serializers/chemicals.py
core/api/views/chemicals.py
core/api/views/cp_report_empty_form.py
core/api/views/utils.py
core/models/base.py
core/models/blend.py

Fixed blends(related to pre-blended polyols ) order

---

core/import_data/import_admb.py
core/import_data/import_admc.py
core/import_data/import_admde.py
core/import_data/import_cp_format.py
core/import_data/import_item_attributes.py
core/import_data/import_records_95_24.py
core/import_data/import_records_section_AB.py
core/import_data/import_records_section_C.py
core/import_data/import_records_section_D.py
core/import_data/import_records_section_E.py
docs/import.md

[#23349](https://helpdesk.eaudeweb.ro/issues/23349#note-10)

Import missing data

---

core/management/commands/export_cp_reports.py
core/management/commands/export_projects.py

https://helpdesk.eaudeweb.ro/issues/21323#note-37

Export cp reports

---

core/api/tests/test_projects.py
core/api/urls.py
core/api/views/projects.py

https://helpdesk.eaudeweb.ro/issues/26569

Project user permissions

---

core/api/export/cp_calculated_amount.py
core/api/export/cp_data_extraction_all.py
core/api/export/cp_report_hfc_hcfc.py
core/api/export/cp_report_new.py
core/api/tests/test_cp_export.py
core/api/views/cp_records_export.py
core/management/commands/export_projects.py

https://helpdesk.eaudeweb.ro/issues/26710
Points 3, 4, 10.

CP export september feedback

---

core/api/export/cp_report_new.py
core/api/export/section_export.py
core/api/serializers/usage.py
core/api/views/cp_records_export.py

5.2 from [#26710](https://helpdesk.eaudeweb.ro/issues/26710)

Updated decimal numbers for cp report export

---

core/api/export/base.py
core/api/export/cp_report_new.py
core/api/export/cp_report_old.py
core/api/export/section_export.py

3 from [#26710](https://helpdesk.eaudeweb.ro/issues/26710)

Fixed cp prices export

---

core/api/tests/base.py
core/api/tests/test_project_comment.py
core/api/tests/test_project_fund.py
core/api/tests/test_project_ods_odp.py
core/api/tests/test_project_rbm_measure.py
core/api/tests/test_project_sub_amount.py
core/api/tests/test_project_utilities.py
core/api/tests/test_projects.py
core/api/tests/test_settings.py
core/api/views/projects.py
core/api/views/sector_subsector.py

[#26715](https://helpdesk.eaudeweb.ro/issues/26715)

Added view permissions for projects (viewer role)

---

core/api/views/cp_archive.py
core/api/views/cp_records_export.py

[26715](https://helpdesk.eaudeweb.ro/issues/26715)

Added more permissions (viewer role)

---

core/api/tests/test_replenishment.py
core/api/views/utils.py
frontend/src/@types/api_replenishment_status_of_contributions.ts
frontend/src/components/manage/Blocks/Replenishment/Dashboard/SectionDashboard.tsx

Also some other small changes:
- add disputed contributions to tabs
- stop using `-` in front of FERM losses

Add ferm to all dashboard tabs

---

core/api/views/cp_reports.py
core/import_data/import_cp_format.py

19. from [#26710](https://helpdesk.eaudeweb.ro/issues/26710)

Mini fix in import cp rep format

---

core/api/serializers/base.py
core/api/serializers/business_plan.py
core/api/tests/test_business_plans.py
core/api/views/business_plan.py

Backend for https://helpdesk.eaudeweb.ro/issues/26880

Update all activities

---

core/api/serializers/cp_history.py
core/api/utils.py
core/api/views/cp_archive.py
core/api/views/cp_records_export.py
frontend/src/@types/store.d.ts
frontend/src/components/manage/Blocks/CountryProgramme/CPView.tsx
frontend/src/components/ui/VersionDetails/VersionHistoryList.tsx

21, 22,23 and 24 from [#26710](https://helpdesk.eaudeweb.ro/issues/26710#note-13)

Small fixes

---

core/api/tests/test_business_plans.py
core/api/tests/test_cp_history.py
core/api/tests/test_cp_records_diff.py
core/api/views/business_plan.py
core/api/views/cp_records.py
core/api/views/cp_reports.py

25. Do not show events like "Status changed from draft to final (Version X)" in history
Also, added `banned_date` to diff response.

Other small feedback changes

---

frontend/src/components/manage/Blocks/Replenishment/Payments/PaymentDialog.tsx
frontend/src/components/manage/Blocks/Replenishment/StatusOfContribution/utils.ts

Also do not modify system-wide years options.

Payments dialog - no FERM calculation for arrears/deferred

---

core/api/export/base.py
core/api/export/business_plan.py
core/api/serializers/business_plan.py
core/api/tests/test_business_plans_export.py
core/api/views/business_plan.py

[26190](https://helpdesk.eaudeweb.ro/issues/26190#note-11)

Added sort order column  in bp export file

---

core/api/tests/test_cp_export.py
core/api/views/cp_records_export.py
core/api/views/utils.py

[#21323](https://helpdesk.eaudeweb.ro/issues/21323#note-39)

Added all substances in the export extractions files

---

core/api/filters/country_programme.py
core/api/serializers/cp_emission.py
core/api/serializers/cp_price.py
core/api/serializers/cp_record.py
core/api/tests/test_cp_prices.py
core/api/urls.py
core/api/views/cp_archive.py
core/api/views/cp_emissions.py
core/api/views/cp_prices.py
core/api/views/cp_records.py
core/api/views/cp_records_export.py
core/api/views/utils.py

[#27988](https://helpdesk.eaudeweb.ro/issues/27988)

New endp dashb

---

core/api/tests/test_business_plans.py
core/api/views/business_plan_utils.py
core/tasks.py

Remove send mail tasks for BP;
Fix `meeting_id` / `decision_id` not setting correctly.

BP small fixes

---

core/api/serializers/base.py
core/api/serializers/cp_emission.py
core/api/serializers/cp_generation.py
core/api/serializers/cp_price.py
core/api/serializers/cp_record.py
core/api/views/cp_emissions_generations.py
core/api/views/cp_prices.py
core/api/views/cp_records.py

https://helpdesk.eaudeweb.ro/issues/27988#note-3

Dashboard endpoints feedback

---

core/api/urls.py
core/api/views/cp_resources.py
docker/nginx-templates/default.nginx.conf.template
frontend/src/components/manage/Blocks/CountryProgramme/CPListing.tsx

https://helpdesk.eaudeweb.ro/issues/27206#note-12

CP resources list

---

frontend/src/components/manage/Blocks/BusinessPlans/BPUpload/BPExport.tsx
frontend/src/components/manage/Blocks/BusinessPlans/BPUpload/BPReviewChanges.tsx

* Download section - remove meeting number
* Review changes section - change label of button from "Change File" to "Back"
- position "Cancel" button to the right

BP Upload Feedback

---

core/admin/time_frame.py
core/admin/usage.py
core/api/tests/test_projects_v2.py
core/api/urls.py
core/api/views/bp_export.py
core/api/views/cp_reports.py
core/api/views/projects.py
core/import_data/import_bp_other_objects.py
core/import_data/import_project_resources.py
core/management/commands/import_all.py
core/management/commands/import_cp_format.py
core/management/commands/import_projects.py
core/management/commands/import_records.py
core/migrations/0118_bpactivityvalue_is_after_and_more.py
core/migrations/0135_update_archives_created_at.py
core/migrations/0163_agency_is_for_replenishment.py
core/migrations/0185_create_triennial_contribution_status_view.py
docs/import.md

* Add base for projects v2 endpoint

Add projects v2 endpoint

---

core/admin/group.py
core/api/serializers/chemicals.py
core/api/tests/test_chemicals.py
core/api/urls.py
core/api/views/chemicals.py

Add group listing endpoint `api/groups/`

Add group listing endpoint

---

core/api/serializers/project_v2.py
core/api/tests/test_projects_v2.py

Added ods_odp on:
* `/api/projects/v2/{id}/`
Partial Response example:
<pre>
...
"ods_odp": [
{
"id": 1234,
"project_id": 4321,
"ods_display_name": "ODS display name 1",
"odp": 11.11,
"ods_replacement": "ods replacement test",
"co2_mt": 323.23,
"ods_type": "production",
"ods_substance_id": 216,
"sort_order": 1
},
{
"id": 1235,
"project_id": 4321,
"ods_display_name": "ODS display name 2",
"odp": 41.41,
"ods_replacement": "ods replacement test 2",
"co2_mt": 543.23,
"ods_type": "general",
"ods_substance_id": 214,
"sort_order": 2
}
...
],
</pre>
* POST /api/projects/v2/
Partial request example:
<pre>
{
...
"total_fund": 2340000,
"ods_odp": [
{
"ods_substance_id": 216,
"odp": 11.11,
"ods_replacement": "ods replacement test",
"co2_mt": 323.23,
"ods_type": "production",
"ods_blend_id": null, …

Add ods_odp to project v2 detail and create endpoints

---

core/api/serializers/business_plan.py
core/api/tests/test_business_plans.py
core/api/views/business_plan_utils.py

Leaving this PR Open in case we want to change the current removal of all activities and recreation on bp revision or import of BP.

Work on bulk update for revision and import of bp activities

---

frontend/src/components/manage/Blocks/ProjectsListing/HelperComponents.tsx
frontend/src/components/manage/Blocks/ProjectsListing/ProjectSubmission/SubmitProjectModal.tsx
frontend/src/components/manage/Blocks/ProjectsListing/ProjectView/ProjectIdentifiers.tsx
frontend/src/components/manage/Blocks/ProjectsListing/ProjectsCreate/ProjectIdentifiersFields.tsx
frontend/src/components/manage/Blocks/ProjectsListing/ProjectsCreate/ProjectOverview.tsx
frontend/src/components/manage/Blocks/ProjectsListing/ProjectsCreate/ProjectsCreate.tsx
frontend/src/components/manage/Blocks/ProjectsListing/ProjectsEdit/ProjectsEdit.tsx
frontend/src/components/manage/Blocks/ProjectsListing/hooks/useGetProjectsForSubmission.ts
frontend/src/components/manage/Blocks/ProjectsListing/interfaces.ts
frontend/src/components/manage/Blocks/ProjectsListing/utils.ts

- Display associated projects (wip)
- Display lead agency and whether it has submitted on behalf of agency

Projects improvements

---

core/api/serializers/agency.py
core/api/tests/test_agency.py
core/api/urls.py
core/api/views/agency.py
core/api/views/countries.py
core/models/agency.py
core/models/country.py

* Added two new endpoints that need to be used in BP module for countries and agencies:
* GET api/business-plan/agencies/
* GET /api/business-plan/countries/

Add bp agency and country endpoints
